import { expect, test, type Page } from '@playwright/test';
import { openQueue, runDelgadoReview, shot, watchConsole } from './helpers';

/**
 * The section 11 script (docs/DEMO_SCRIPT.md), beat by beat. Each step
 * asserts what should appear and captures a screenshot into docs/screenshots.
 */
test.describe('four-minute demo script', () => {
  test('runs start to finish with no dead end', async ({ page }) => {
    const { errors, requests } = watchConsole(page);

    // 0:00 Start on the Queue.
    await openQueue(page);
    const rows = page.locator('[data-queue-table] tbody tr');
    await expect(rows).toHaveCount(7);
    await expect(rows.nth(0)).toHaveAttribute('data-case-row', 'MIA-2026-1187');
    await expect(rows.nth(0)).toHaveAttribute('data-status', 'new');
    await expect(rows.nth(0)).toContainText('Delgado residence');
    await expect(rows.nth(0)).toContainText('Not yet reviewed.');
    await expect(rows.nth(1)).toHaveAttribute('data-status', 'approve_ready');
    await expect(rows.nth(2)).toHaveAttribute('data-status', 'approve_ready');
    await expect(page.locator('[data-summary]')).toHaveText('7 open cases: 1 new, 2 approve-ready, 2 need information, 2 need judgment.');
    await expect(page.getByText('New here? Start with Run review on the Delgado case.')).toBeVisible();
    await expect(page.locator('[data-prototype-tag]')).toBeVisible();
    await shot(page, '01-queue');

    // 0:20 Run review on the Delgado row.
    await page.locator('[data-case-row="MIA-2026-1187"] [data-run-review]').click();
    const progress = page.locator('dialog[data-dialog="run-review"]');
    await expect(progress.getByText('Reading 7 documents')).toBeVisible();
    await expect(progress.getByText('Checking 12 criteria against Rulebook v1.0')).toBeVisible();
    await expect(progress.getByText('Finding similar past decisions')).toBeVisible();
    await expect(progress.locator('[data-step-state="done"]')).toHaveCount(1, { timeout: 4000 });
    await shot(page, '02-run-review');
    await expect(progress.locator('[data-step-state="done"]')).toHaveCount(2, { timeout: 6000 });
    await expect(progress.locator('[data-step-state="done"]')).toHaveCount(3, { timeout: 6000 });
    await expect(page).toHaveURL(/#\/cases\/MIA-2026-1187/, { timeout: 8000 });
    const savedTag = page.locator('[data-saved-review]');
    await expect(savedTag).toBeVisible();
    await savedTag.hover();
    const tooltip = page.getByRole('tooltip').filter({ hasText: 'Generated by Claude' });
    await expect(tooltip).toHaveText('Generated by Claude from these documents, then saved so the demo is repeatable.');
    await expect.poll(() => tooltip.evaluate((el) => getComputedStyle(el).opacity)).toBe('1');
    await page.mouse.move(700, 450);

    // 0:35 Left pane, then A3 at Second reader.
    await expect(page.locator('[data-criteria-count]')).toHaveText('12 criteria: 9 met, 3 flagged.');
    await expect(page.locator('[data-criterion="A3"]')).toHaveAttribute('aria-selected', 'true');
    await expect(page.locator('[data-rule-card="A3"]')).toContainText('Setbacks');
    await expect(page.locator('[data-rule-card="A3"] [data-rung-tag]')).toHaveText('Second reader');
    const marks = page.locator('mark[data-evidence]');
    await expect(marks).toHaveCount(2);
    await expect(marks.nth(0)).toContainText('5 ft 0 in');
    await expect(marks.nth(1)).toContainText('4 ft 6 in');
    await page.waitForTimeout(600);
    await expect(marks.nth(0)).toBeInViewport();
    await expect(marks.nth(1)).toBeInViewport();
    await expect(page.locator('[data-recommendation-gate]')).toContainText('Open the flagged criteria to see the recommendation (2 left)');
    await shot(page, '03-case-review-a3');

    // 0:35 (cont.) Source chip, then past decisions.
    await page.getByRole('button', { name: 'Open source R1 §ADU-3' }).click();
    const drawer = page.locator('dialog[data-drawer="source"]');
    await expect(drawer).toBeVisible();
    await expect(drawer).toContainText('Zoning code: accessory dwelling units (excerpt)');
    await expect(drawer.locator('[data-section="§ADU-3"]')).toHaveAttribute('data-highlighted', 'true');
    await expect(drawer.locator('[data-section="§ADU-3"]')).toContainText('at least 5 feet from the side and rear lot lines');
    await shot(page, '04-source-viewer');
    await page.keyboard.press('Escape');
    await expect(drawer).toBeHidden();
    const precedents = page.locator('[data-rule-card="A3"] [data-precedent]');
    await expect(precedents).toHaveCount(4);
    await expect(page.locator('[data-rule-card="A3"] [data-precedents]').getByText('Approved with waiver')).toHaveCount(3);
    await expect(page.locator('[data-rule-card="A3"] [data-precedents]').getByText('Denied')).toHaveCount(1);

    // 1:10 Next flagged: A5.
    await page.locator('[data-next-flagged]').click();
    await expect(page.locator('[data-criterion="A5"]')).toHaveAttribute('aria-selected', 'true');
    await expect(page.locator('[data-rule-card="A5"]')).toContainText('Flood elevation');
    await expect(page.locator('[data-rule-card="A5"]')).toContainText('Not met');
    const missing = page.locator('[data-missing][data-document="Elevation certificate"]');
    await expect(missing).toContainText('Not provided');
    await page.waitForTimeout(600);
    await expect(missing).toBeInViewport();
    await expect(page.locator('[data-recommendation-gate]')).toContainText('(1 left)');
    await shot(page, '05-case-review-a5');

    // 1:20 Next flagged: X1.
    await page.locator('[data-next-flagged]').click();
    await expect(page.locator('[data-criterion="X1"]')).toHaveAttribute('aria-selected', 'true');
    await expect(page.locator('[data-rule-card="X1"]')).toContainText('Electrical capacity');
    await expect(page.locator('[data-rule-card="X1"]')).toContainText('Not met');
    const x1Marks = page.locator('mark[data-evidence]');
    await expect(x1Marks).toHaveCount(2);
    await expect(x1Marks.nth(0)).toHaveText('Total with the ADU: 144 A, within the 150 A service.');
    await expect(x1Marks.nth(1)).toHaveText('Main breaker derated to 125 A for a 40 A solar backfeed breaker.');
    await expect(page.locator('[data-rule-card="X1"] [data-rung-tag]')).toHaveCount(0);
    await page.waitForTimeout(600);
    await expect(x1Marks.nth(0)).toBeInViewport();
    await expect(x1Marks.nth(1)).toBeInViewport();
    await expect(page.locator('[data-rule-card="X1"] [data-precedent]')).toHaveCount(1);
    await expect(page.locator('[data-next-flagged]')).toBeDisabled();
    await shot(page, '06-case-review-x1');

    // 1:50 The recommendation reveals. Replace the bracketed line, then send.
    const recommendation = page.locator('[data-recommendation]');
    await expect(recommendation).toBeVisible();
    await expect(recommendation).toContainText('Needs judgment');
    await expect(page.locator('[data-rationale]')).toContainText('Nine of the twelve criteria are met');
    const actions = page.locator('[data-actions]');
    await expect(actions.locator('[data-action="approve"]')).toBeVisible();
    await expect(actions.locator('[data-action="send"]')).toBeVisible();
    await expect(actions.locator('[data-action="escalate"]')).toBeVisible();
    await expect(actions.locator('[data-action="send"]')).toHaveAttribute('aria-disabled', 'true');
    await expect(page.locator('[data-send-hint]')).toHaveText('Replace the bracketed note first.');
    const letter = page.locator('[data-letter-editor] textarea');
    await expect(page.locator('[data-letter-editor] [data-bracket]')).toHaveCount(1);
    const draft = await letter.inputValue();
    await letter.fill(draft.replace('[Reviewer to decide: invite an administrative waiver request, or require a revised site plan.]', 'You may apply for an administrative waiver for the rear setback.'));
    await expect(page.locator('[data-letter-editor] [data-bracket]')).toHaveCount(0);
    await expect(actions.locator('[data-action="send"]')).not.toHaveAttribute('aria-disabled', 'true');
    const sendOptions = page.locator('[data-send-options]');
    await sendOptions.scrollIntoViewIfNeeded();
    await expect(sendOptions.getByLabel('Reply due')).toHaveValue('2026-10-05');
    await expect(sendOptions.getByLabel('Email')).toBeChecked();
    await expect(sendOptions.getByLabel('Text message')).toBeChecked();
    await expect(sendOptions.getByLabel('Phone call from a virtual agent')).not.toBeChecked();
    await expect(sendOptions.getByText('Sent 5 and 9 business days after the request. Reminders stop when the applicant replies. Automated calls say they are automated.')).toBeVisible();
    await expect(sendOptions.getByLabel('Also send a Spanish copy')).toBeChecked();
    await expect(sendOptions.getByText('The English letter is the official version. The copy updates to match your edits when sent.')).toBeVisible();
    await shot(page, '07-recommendation');
    await sendOptions.locator('[data-preview-spanish]').click();
    const letterDrawer = page.locator('dialog[data-drawer="letter"]');
    await expect(letterDrawer).toBeVisible();
    await expect(letterDrawer.locator('[data-letter-preview="es"]')).toContainText('Certificado de elevación');
    await expect(letterDrawer.locator('[data-letter-preview="es"]')).toContainText('5 de octubre de 2026');
    await shot(page, '08-spanish-letter');
    await page.keyboard.press('Escape');
    await expect(letterDrawer).toBeHidden();
    await actions.locator('[data-action="send"]').click();
    const toast = page.locator('[data-toast]').first();
    await expect(toast).toContainText('Request sent to Maria Delgado.');
    await expect(toast.getByRole('button', { name: /Undo/ })).toBeVisible();
    await expect(page).toHaveURL(/#\/$/);
    await shot(page, '09-queue-after-send');

    // 1:50 (cont.) Decision record on the Delgado row: spoken over in the script, opened here to check it.
    const delgadoRow = page.locator('[data-case-row="MIA-2026-1187"]');
    await expect(delgadoRow).toHaveAttribute('data-status', 'waiting');
    await expect(delgadoRow).toContainText('Waiting on applicant');
    await expect(delgadoRow).toContainText('Reply due 5 Oct 2026');
    await expect(delgadoRow).toContainText('paused');
    await expect(page.locator('[data-summary]')).toHaveText('7 open cases: 2 approve-ready, 2 need information, 2 need judgment, 1 waiting on applicant.');
    await delgadoRow.locator('[data-decision-record]').click();
    const record = page.locator('dialog[data-drawer="record"]');
    await expect(record).toBeVisible();
    for (const item of ['Review generated', 'Rulebook v1.0', 'Criteria opened', 'A3, A5, X1', 'Letter edited', 'Request for information sent', 'Reply due', 'Reminders scheduled', '28 Sep 2026 and 2 Oct 2026', 'Spanish copy', 'Reviewer', 'J. Rivera', 'Letter as sent']) {
      await expect(record).toContainText(item);
    }
    await shot(page, '10-decision-record');
    await page.keyboard.press('Escape');
    await expect(record).toBeHidden();

    // 2:35 Rulebook: add the bulletin, approve the change. (The Undo toast has drained by now.)
    await expect(page.locator('[data-toast]')).toHaveCount(0, { timeout: 12000 });
    await page.getByRole('link', { name: 'Rulebook' }).first().click();
    await expect(page.locator('[data-rulebook-headline]')).toHaveText('Rulebook v1.0, approved by policy staff');
    await expect(page.locator('[data-sources-table] tbody tr')).toHaveCount(5);
    await page.locator('[data-add-source]').click();
    await page.locator('[data-load-example]').click();
    await expect(page.locator('[data-source-name]')).toHaveValue('Fire Marshal bulletin 2026-03: rooftop access pathways');
    await page.locator('[data-add-confirm]').click();
    const r6 = page.locator('[data-source-row="R6"]');
    await expect(r6).toBeVisible();
    await expect(r6.locator('[data-processing]')).toContainText('Processing');
    await expect(r6.locator('[data-proposed-change]')).toContainText('1 proposed change', { timeout: 6000 });
    await shot(page, '11-rulebook-proposed');
    await r6.locator('[data-proposed-change]').click();
    const change = page.locator('dialog[data-dialog="proposed-change"]');
    await expect(change).toBeVisible();
    await expect(change.locator('[data-current-test]')).toContainText('36 in pathway from eave to ridge and an 18 in ridge setback');
    await expect(change.locator('[data-proposed-test]')).toContainText('36 in pathway from eave to ridge. Ridge setback of 18 in, or 36 in when the array covers more than 33% of the roof.');
    await expect(change).toContainText('R6 §2');
    await expect(change.locator('[data-impact-line]')).toHaveText('On closed cases, 37 of 1,200 outcomes would have differed. 5 open solar cases were filed earlier and keep v1.0.');
    await expect(change.getByLabel('Applies to applications filed on or after')).toHaveValue('2026-09-22');
    await expect(change).toContainText('Earlier applications keep Rulebook v1.0. No rule changes in the middle of an application.');
    await shot(page, '12-proposed-s2-change');
    await change.locator('[data-approve-change]').click();
    await expect(page.locator('[data-toast]').last()).toContainText('Rulebook v1.1 published by J. Okafor. It applies to applications filed from 22 Sep 2026.');
    await expect(page.locator('[data-rulebook-version]')).toHaveText('Rulebook v1.1');
    await expect(page.locator('[data-rulebook-headline]')).toContainText('Rulebook v1.1');
    await expect(r6).toContainText('Active');
    await page.getByRole('tab', { name: 'Criteria' }).click();
    await expect(page.locator('[data-criterion-row="S2"] [data-updated-tag]')).toHaveText('Updated in v1.1');
    await expect(page.locator('[data-criterion-row="S2"]')).toContainText('R6 §2');
    await shot(page, '13-rulebook-criteria-v11');

    // 3:10 Proving ground: agreement and golden set; settle the first X1 row.
    await page.getByRole('link', { name: 'Proving ground' }).first().click();
    await expect(page.locator('[data-headline]')).toHaveText('A sample of 1,200 closed cases from 2024 to 2025. Claude agreed with the original decision on 91%.');
    await expect(page.locator('[data-floor]')).toHaveText('Agreement is not accuracy. Senior reviewers settle every disagreement blind, and relabel a random sample of agreed cases, so shared mistakes count too. On that golden set, Claude is right on 95%.');
    await expect(page.locator('[data-readiness]')).toHaveText('Threshold for First review: 90% on the golden set, per criterion. 11 of 12 met.');
    await expect(page.locator('[data-agreement="X1"]')).toContainText('79%');
    await expect(page.locator('[data-agreement="X1"] [data-golden-value]')).toHaveText('94%');
    await expect(page.locator('[data-agreement="A3"]')).toHaveAttribute('data-below', 'true');
    await expect(page.locator('[data-tally]')).toContainText('100 of 108 settled: Claude right 46, reviewer right 48, unclear 6');
    const x1Row = page.locator('[data-disagreement]').filter({ hasText: 'X1' }).first();
    await expect(x1Row).toContainText('A: both permits approved separately.');
    await expect(x1Row).toContainText('B: the solar derate leaves the main breaker too small for the ADU load.');
    await expect(page.locator('[data-toast]')).toHaveCount(0, { timeout: 12000 });
    await shot(page, '14-proving-ground');
    await x1Row.locator('[data-settle="b"]').click();
    await expect(x1Row.locator('[data-reveal]')).toHaveText('B was Claude');
    await expect(x1Row).toHaveAttribute('data-settled', 'true');
    await expect(page.locator('[data-tally]')).toContainText('101 of 108 settled: Claude right 47, reviewer right 48, unclear 6', { timeout: 5000 });
    await expect(page.locator('[data-tally]')).toContainText('Settled cases become the golden set.');
    await shot(page, '15-proving-ground-settled');

    // 3:45 Scoreboard: tiles, comparison group, ladder, model switch, move A3 up.
    await expect(page.locator('[data-toast]')).toHaveCount(0, { timeout: 8000 });
    await page.getByRole('link', { name: 'Scoreboard' }).first().click();
    await expect(page.locator('[data-metric="days"] [data-current]')).toHaveText('21');
    await expect(page.locator('[data-metric="days"]')).toContainText('Baseline 34');
    await expect(page.locator('[data-metric="backlog"] [data-current]')).toHaveText('286');
    await expect(page.locator('[data-metric="backlog"]')).toContainText('Baseline 412');
    await expect(page.locator('[data-metric="rework"] [data-current]')).toHaveText('24%');
    await expect(page.locator('[data-metric="rework"]')).toContainText('Baseline 38%');
    await expect(page.locator('[data-metric="known"] [data-current]')).toHaveText('96.1%');
    await expect(page.locator('[data-metric="known"]')).toContainText('Baseline 95.2%');
    await expect(page.locator('[data-usage-line]')).toContainText('Cases reviewed with Casework this quarter: 1,482.');
    await expect(page.locator('[data-override-line]')).toContainText("Reviewer changes to Claude's findings: 11%.");
    await expect(page.locator('[data-override-line]')).toContainText('A rate near zero would suggest rubber-stamping.');
    await expect(page.locator('[data-team-footnote]')).toHaveText('All figures are for the team. Casework does not rank individual reviewers.');
    await expect(page.locator('[data-team-footnote]')).toBeInViewport();
    await expect(page.getByText('First review switched on')).toBeVisible();
    const frontDoor = page.locator('[data-rung="front_door"]');
    await expect(frontDoor).toContainText('Locked');
    await expect(frontDoor.getByRole('switch')).toBeDisabled();
    await expect(page.locator('[data-metric="days"]')).toContainText('Permit types not yet on Casework: 34 to 33');
    await expect(page.locator('[data-first-review-coverage]')).toHaveText('On for 11 of 12 criteria. A3 Setbacks at Second reader.');
    await expect(page.locator('[data-model-text]')).toHaveText('A new model is available. Golden set: 95% to 97%. No criterion got worse.');
    await expect(page.locator('[data-model-sub]')).toContainText('A3 Setbacks rises from 88% to 91%, above the 90% threshold.');
    await shot(page, '16-scoreboard');
    await page.locator('[data-approve-switch]').click();
    await expect(page.locator('[data-model-text]')).toHaveText('Switched to the new model. The rulebook is unchanged.');
    await expect(page.locator('[data-model-sub]')).toHaveText("A3 Setbacks now clears the 90% threshold. Moving it up is the director's call.");
    await expect(page.locator('[data-first-review-coverage]')).toHaveText('On for 11 of 12 criteria. A3 Setbacks at Second reader.');
    await page.locator('[data-move-up]').click();
    await expect(page.locator('[data-first-review-coverage]')).toHaveText('On for all 12 criteria.');
    await expect(page.locator('[data-toast]').last()).toContainText('A3 Setbacks moved to First review.');
    await expect(page.locator('[data-move-up]')).toHaveCount(0);
    await shot(page, '17-scoreboard-switched');

    // 4:20 Stay on the Scoreboard. No change.
    await expect(page.locator('[data-prototype-tag]')).toBeVisible();

    expect(errors, `console errors: ${errors.join('\n')}`).toEqual([]);
    expect(requests, `external requests: ${requests.join('\n')}`).toEqual([]);
  });

  test('Reset demo restores the starting state', async ({ page }) => {
    await openQueue(page);
    await runDelgadoReview(page);
    await page.getByRole('button', { name: 'Reset demo' }).click();
    await expect(page).toHaveURL(/#\/$/);
    await expect(page.locator('[data-summary]')).toHaveText('7 open cases: 1 new, 2 approve-ready, 2 need information, 2 need judgment.');
    await expect(page.getByText('New here? Start with Run review on the Delgado case.')).toBeVisible();
    await expect(page.locator('[data-case-row="MIA-2026-1187"] [data-run-review]')).toBeVisible();
  });
});

export async function undoSend(page: Page): Promise<void> {
  await page.locator('[data-toast]').first().getByRole('button', { name: /Undo/ }).click();
}
