import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ChevronRight, Info } from 'lucide-react';
import { useStore } from '@/app/store';
import { CASES_BY_ID } from '@/data/cases';
import { PACKETS } from '@/data/packets';
import type { CriterionId } from '@/data/types';
import { Tag } from '@/components/ui/Chip';
import { Tooltip } from '@/components/ui/Tooltip';
import { EmptyState } from '@/components/ui/EmptyState';
import { buildCriteriaViews, countsLine, initialSelection, nextFlagged, unopenedFlagged } from '@/lib/caseReview';
import { CriteriaPane } from './CriteriaPane';
import { EvidencePane } from './EvidencePane';
import { RecommendationPane } from './RecommendationPane';
import { NotCoveredDialog } from './dialogs';
import styles from './CaseReviewScreen.module.css';

export const SAVED_REVIEW_TOOLTIP = 'Generated by Claude from these documents, then saved so the demo is repeatable.';

/** The hero screen. Reads left to right: what was checked, what the evidence says, what to do. */
export function CaseReviewScreen() {
  const { caseId = '' } = useParams();
  const meta = CASES_BY_ID[caseId];
  const packet = PACKETS[caseId];
  const caseState = useStore((s) => s.cases[caseId]);
  const loadReview = useStore((s) => s.loadReview);
  const openCriterion = useStore((s) => s.openCriterion);
  const reveal = useStore((s) => s.reveal);
  const s2Test = useStore((s) => s.s2Test);
  const published = useStore((s) => s.rulebookVersion === '1.1');
  const drawerOpen = useStore((s) => s.drawer !== null);
  const [selectedId, setSelectedId] = useState<CriterionId | null>(null);
  const [notCoveredOpen, setNotCoveredOpen] = useState(false);

  useEffect(() => {
    if (meta && !caseState?.review) void loadReview(caseId);
  }, [caseId, caseState?.review, loadReview, meta]);

  const review = caseState?.review;
  const applyS2 = published && meta ? false : false;
  const views = useMemo(() => (review ? buildCriteriaViews(review, caseState?.changes ?? {}, applyS2 ? s2Test : undefined) : []), [review, caseState?.changes, applyS2, s2Test]);

  useEffect(() => {
    if (views.length > 0 && selectedId === null) {
      const first = initialSelection(views);
      if (first) setSelectedId(first);
    }
  }, [views, selectedId]);

  useEffect(() => {
    if (selectedId) openCriterion(caseId, selectedId);
  }, [selectedId, caseId, openCriterion]);

  const opened = caseState?.openedCriteria ?? [];
  const remaining = useMemo(() => unopenedFlagged(views, opened), [views, opened]);

  useEffect(() => {
    if (views.length > 0 && remaining.length === 0 && caseState && !caseState.revealed) reveal(caseId);
  }, [views.length, remaining.length, caseState, reveal, caseId]);

  const select = useCallback((id: CriterionId) => setSelectedId(id), []);
  const next = nextFlagged(views, selectedId);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (drawerOpen || notCoveredOpen) return;
      const target = e.target as HTMLElement | null;
      if (target && (target.closest('input, textarea, select, [contenteditable="true"], dialog') || target.isContentEditable)) return;
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault();
        const index = views.findIndex((v) => v.id === selectedId);
        const nextIndex = e.key === 'ArrowDown' ? Math.min(views.length - 1, index + 1) : Math.max(0, index - 1);
        const v = views[nextIndex];
        if (v) setSelectedId(v.id);
      } else if (e.key === 'n' || e.key === 'N') {
        if (next) {
          e.preventDefault();
          setSelectedId(next);
        }
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [views, selectedId, next, drawerOpen, notCoveredOpen]);

  if (!meta || !packet) {
    return (
      <div className={styles.screen}>
        <EmptyState title="Case not found" description="Choose a case from the queue." action={<Link to="/">Back to Queue</Link>} />
      </div>
    );
  }

  const selected = views.find((v) => v.id === selectedId) ?? null;

  return (
    <div className={styles.screen} data-case-review={caseId}>
      <header className={styles.header}>
        <nav className={styles.breadcrumb} aria-label="Breadcrumb">
          <Link to="/" className={styles.crumb}>
            Queue
          </Link>
          <ChevronRight size={14} aria-hidden className={styles.crumbSep} />
          <span className={styles.crumbCurrent} aria-current="page">
            {meta.id}
          </span>
        </nav>
        <div className={styles.headerMain}>
          <h1 className={styles.title}>{meta.applicant}</h1>
          <span className={styles.headerMeta}>{meta.typeLabel}</span>
          <span className={styles.headerDot} aria-hidden>
            ·
          </span>
          <span className={styles.headerMeta}>{meta.daysInQueue === 0 ? 'Filed today' : `${meta.daysInQueue} days in queue`}</span>
          <span className={styles.headerDot} aria-hidden>
            ·
          </span>
          <span className={styles.headerMeta}>{meta.address}</span>
        </div>
        <div className={styles.headerRight}>
          {review && (
            <Tooltip text={SAVED_REVIEW_TOOLTIP} align="end">
              <Tag icon={Info} data-saved-review>
                Saved review
              </Tag>
            </Tooltip>
          )}
        </div>
      </header>

      {!review || !caseState ? (
        <div className={styles.loading} aria-busy="true">
          Loading the saved review
        </div>
      ) : (
        <div className={styles.panes}>
          <CriteriaPane views={views} selectedId={selectedId} onSelect={select} countsLine={countsLine(views)} onNotCovered={() => setNotCoveredOpen(true)} />
          <EvidencePane caseId={caseId} packet={packet} selected={selected} next={next} onNext={() => next && setSelectedId(next)} />
          <RecommendationPane caseId={caseId} meta={meta} caseState={caseState} views={views} remaining={remaining.length} />
        </div>
      )}
      <NotCoveredDialog open={notCoveredOpen} onClose={() => setNotCoveredOpen(false)} />
    </div>
  );
}
