// Writes docs/DEMO_SCRIPT_SAY_ONLY.md from docs/DEMO_SCRIPT.md: the same beats
// and spoken lines, with the Do lines and setup notes taken out. With --check,
// fails instead of writing when the committed copy has drifted from the script.
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'docs/DEMO_SCRIPT.md';
const TARGET = 'docs/DEMO_SCRIPT_SAY_ONLY.md';

const source = readFileSync(SOURCE, 'utf8');
const beats = [];
let heading = null;
for (const line of source.split('\n')) {
  if (line.startsWith('## ') && heading) break;
  if (line.startsWith('### ')) heading = line.slice(4).trim();
  const say = line.match(/^\*\*Say\.\*\* "(.*)"$/);
  if (say && heading) beats.push({ heading, text: say[1] });
}
if (beats.length === 0) {
  console.error(`${SOURCE}: no **Say.** lines found under ### beat headings.`);
  process.exit(1);
}

const out = [
  '# Casework: the demo script, spoken lines only',
  '',
  `Every spoken line from [\`DEMO_SCRIPT.md\`](DEMO_SCRIPT.md), in order, with the clicks taken out. Timestamps match the silent recording in \`docs/walkthrough.mp4\`. Generated by \`npm run docs:say-only\`; edit the full script, not this file.`,
  '',
  ...beats.flatMap((b) => [`## ${b.heading}`, '', b.text, '']),
].join('\n');

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(TARGET, 'utf8');
  } catch {
    console.error(`${TARGET} is missing. Run npm run docs:say-only.`);
    process.exit(1);
  }
  if (current !== out) {
    console.error(`${TARGET} is out of date with ${SOURCE}. Run npm run docs:say-only.`);
    process.exit(1);
  }
  console.log(`${TARGET} matches ${SOURCE} (${beats.length} beats).`);
} else {
  writeFileSync(TARGET, out);
  console.log(`${TARGET} written (${beats.length} beats).`);
}
